-- vim.keymap.set('n', '<leader><leader>x', "<cmd>source %<CR>", { desc = 'E[x]ecute current file' })
-- vim.keymap.set('n', '<leader>x', ":.lua<CR>", { desc = "E[x]ecute current line" })
-- vim.keymap.set('v', '<leader>x', ":lua<CR>", { desc = "E[x]ecute selected lines" })
